version: "3"

services:
  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 9540:9540
    volumes:
      - upload:/usr/share/nginx/html/static
    depends_on:
      - servers

  servers:
    build:
      context: ./apps/servers
      dockerfile: ./Dockerfile
    command: npm run start:docker
    restart: always
    ports:
      - 8080:8080
    volumes:
      - upload:/upload
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8.3.0
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    ports:
      - 3308:3306 # 规避外部mysql端口
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "nest_rbac"
    volumes:
      - mysql:/var/lib/mysql
      - ./db/nest_rbac.sql:/docker-entrypoint-initdb.d/nest_rbac.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8088:8080

  redis:
    image: redis:5-alpine
    restart: always
    ports:
      - 6378:6379 # 规避外部redis端口
    volumes:
      - redis:/data

volumes:
  mysql:
  redis:
  upload:
