name: Deploy Node.js App

# 触发条件：当 main 分支有 push 操作时
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    # 第一步，检查出最新代码
    - name: Checkout code
      uses: actions/checkout@v2

    # 第二步，通过 SSH 连接到远程服务器，部署代码
    - name: Deploy to Server
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.HOST }} # 在GitHub Secrets中配置的服务器IP地址
        username: ${{ secrets.USERNAME }} # 在GitHub Secrets中配置的服务器用户名
        key: ${{ secrets.SSH_PRIVATE_KEY }} # 在GitHub Secrets中配置的SSH私钥
        port: ${{ secrets.PORT }} # 在GitHub Secrets中配置的SSH端口，默认22
        script: |
          cd /www/wwwroot/nestJs-backend   
          git pull origin main 
          npm i pnpm pm2 -g          
          pnpm install                
          pnpm run server:build             
          pnpm run pm2:start 
